name: this is a exmaple file
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test1
        run: |
          echo $MY_SECRETS
        env:
          MY_SECRETS: ${{ secrets.PRABIN }}
